### ISSUE TITLE
Layer order - landformLine above landformArea

### ISSUE THREAD

**Issue by jnflint** [tombrennan06/qgis-nsw-topo#2]
Can I suggest that the landformLine layer be placed above landformArea.
The jagged parts of the cliffline are obscured otherwise.
Not sure of any cases where the current layer order would be preferred.
See pics
![image](https://github.com/tombrennan06/qgis-nsw-topo/assets/6857696/cd6fabe8-b33a-4221-be60-e7c9fdf7d804)
![image](https://github.com/tombrennan06/qgis-nsw-topo/assets/6857696/17e8dd02-b6c7-4bd0-97f6-b4b9db6d8f67)

**Comment by tombrennan06** [comment]
Moved landformLine and landformPoint layers up
